// Generates robots.txt and sitemap.xml at build time.
//
// These have to be generated rather than checked in, because both need the
// deployment's real origin — a sitemap with the wrong hostname is ignored by
// Google, and a hand-maintained robots.txt drifts from the router.
//
// Two knobs, both read from the CRA env (.env / .env.production / host panel):
//
//   REACT_APP_SITE_URL       the canonical origin, e.g. https://e360.app
//   REACT_APP_SEO_INDEXABLE  "false" turns the whole deploy off for crawlers
//
// The indexable switch exists because this app is deployed once per shop. Only
// the public-facing deploy should ever be crawled; a shop's own instance is a
// private business tool and must stay out of the index entirely.

const fs = require("fs");
const path = require("path");

// CRA loads .env files itself, but this script runs before that — so read them
// here, in the same precedence order CRA uses.
//
// We parse and merge by hand rather than calling dotenv.config(): the pinned
// dotenv is v10, where config() never overwrites an already-set variable and
// the `override` option does not exist yet. Loading .env first would then
// silently win over .env.production and every build would use the dev values.
function readEnvFile(file) {
  const full = path.join(__dirname, "..", file);
  if (!fs.existsSync(full)) return {};
  return require("dotenv").parse(fs.readFileSync(full));
}

const isDev = process.env.NODE_ENV === "development";

// Lowest to highest: .env, then .env.production, then anything already exported
// in the real environment (a Vercel/Hostinger panel variable must win).
const env = {
  ...readEnvFile(".env"),
  ...(isDev ? {} : readEnvFile(".env.production")),
};
["REACT_APP_SITE_URL", "REACT_APP_SEO_INDEXABLE"].forEach((key) => {
  if (process.env[key] !== undefined) env[key] = process.env[key];
});

const PUBLIC_DIR = path.join(__dirname, "..", "public");

// Trailing slashes break URL joins and produce "https://site.com//page".
const SITE_URL = (env.REACT_APP_SITE_URL || "").trim().replace(/\/+$/, "");
const INDEXABLE = (env.REACT_APP_SEO_INDEXABLE || "true").trim() !== "false";

// Every path a crawler is allowed to see. Deliberately tiny: the app has
// exactly one public page. /LoginPage is public but worthless in search
// results, and /about is still a stub — both stay out.
const PUBLIC_PATHS = ["/"];

// Route prefixes that must never be crawled. Kept in sync with App.jsx.
const PRIVATE_PREFIXES = [
  "/AdminDashboard",
  "/ManagerDashboard",
  "/SuperAdmin",
  "/StaffDashboard",
  "/pos",
  "/LoginPage",
  "/api",
];

function buildRobots() {
  if (!INDEXABLE) {
    return [
      "# This deployment is a private shop instance — not for indexing.",
      "User-agent: *",
      "Disallow: /",
      "",
    ].join("\n");
  }

  const lines = [
    "# Generated by scripts/generate-seo.js — do not edit by hand.",
    "User-agent: *",
  ];

  // Allow the public page explicitly before the disallows, so the intent is
  // readable to a human auditing this file.
  lines.push("Allow: /$");
  PRIVATE_PREFIXES.forEach((prefix) => lines.push(`Disallow: ${prefix}`));

  lines.push("");
  if (SITE_URL) {
    lines.push(`Sitemap: ${SITE_URL}/sitemap.xml`);
    lines.push("");
  }

  return lines.join("\n");
}

function buildSitemap() {
  // A sitemap without an absolute origin is invalid, and one for a deploy we
  // don't want crawled is worse than none.
  if (!SITE_URL || !INDEXABLE) return null;

  const lastmod = new Date().toISOString().split("T")[0];
  const urls = PUBLIC_PATHS.map((p) => {
    const loc = p === "/" ? `${SITE_URL}/` : `${SITE_URL}${p}`;
    return [
      "  <url>",
      `    <loc>${loc}</loc>`,
      `    <lastmod>${lastmod}</lastmod>`,
      "    <changefreq>weekly</changefreq>",
      "    <priority>1.0</priority>",
      "  </url>",
    ].join("\n");
  }).join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

fs.writeFileSync(path.join(PUBLIC_DIR, "robots.txt"), buildRobots(), "utf8");

const sitemapPath = path.join(PUBLIC_DIR, "sitemap.xml");
const sitemap = buildSitemap();
if (sitemap) {
  fs.writeFileSync(sitemapPath, sitemap, "utf8");
} else if (fs.existsSync(sitemapPath)) {
  // A stale sitemap from a previous indexable build must not ship with a
  // build that is meant to be invisible.
  fs.unlinkSync(sitemapPath);
}

if (!SITE_URL) {
  console.warn(
    "[seo] REACT_APP_SITE_URL is not set — skipping sitemap.xml and the " +
      "canonical URL. Search Console will not accept the site until it is set."
  );
}
console.log(
  `[seo] robots.txt written (indexable=${INDEXABLE})` +
    (sitemap ? `, sitemap.xml → ${SITE_URL}/` : "")
);
