const mongoose = require("mongoose");

// A Receipt is the source of truth for one POS transaction (the whole basket).
// The per-line Sale documents are still written for the existing sales/report
// screens, and are linked back here via saleIds.
const ReceiptItemSchema = new mongoose.Schema(
  {
    product: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true },
    name: { type: String },
    barcode: { type: String },
    quantity: { type: Number, required: true },
    price: { type: Number, required: true },
    lineTotal: { type: Number, required: true },
  },
  { _id: false }
);

const RefundEntrySchema = new mongoose.Schema(
  {
    // The refund's own number, quoted the way a receipt number is. Sequential
    // and independent of the receipt, because one receipt can be refunded more
    // than once and "the refund on POS-000036" stops identifying anything the
    // second time it happens.
    reference: { type: String },
    at: { type: Date, default: Date.now },
    by: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    byName: { type: String },
    reason: { type: String },
    // How the money actually went back. Not always how it came in: a card sale
    // handed back in cash is an ordinary thing at a counter, and the drawer
    // needs to know which it was.
    method: { type: String, enum: ["cash", "creditcard", "credit", "wallet"] },
    amount: { type: Number, default: 0 },
    items: [
      {
        _id: false,
        product: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
        name: { type: String },
        quantity: { type: Number },
        lineTotal: { type: Number },
      },
    ],
  },
  { _id: false }
);

const ReceiptSchema = new mongoose.Schema(
  {
    receiptNo: { type: String, required: true, unique: true },
    cashier: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    cashierName: { type: String },
    customerName: { type: String, default: "Walk-in Customer" },

    items: [ReceiptItemSchema],

    subtotal: { type: Number, default: 0 },
    discount: { type: Number, default: 0 },
    discountType: { type: String, enum: ["amount", "percent"], default: "amount" },

    // The offers the cashier gave on this basket. dealDiscount is the portion
    // of `discount` that came from them.
    dealDiscount: { type: Number, default: 0 },
    deals: [
      {
        _id: false,
        dealId: { type: mongoose.Schema.Types.ObjectId, ref: "Deal" },
        name: { type: String },
        sets: { type: Number, default: 1 },
        amount: { type: Number, default: 0 },
        // Which units the offer actually covered. Five items on a 3-for deal
        // are three at the deal and two at shelf price, and a customer reading
        // this back has to be able to see which were which.
        items: [
          {
            _id: false,
            product: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
            name: { type: String },
            quantity: { type: Number },
          },
        ],
      },
    ],
    voucher: {
      code: { type: String },
      voucherId: { type: mongoose.Schema.Types.ObjectId, ref: "Voucher" },
      amount: { type: Number, default: 0 },
    },

    taxEnabled: { type: Boolean, default: false },
    taxRate: { type: Number, default: 0 },
    tax: { type: Number, default: 0 },

    total: { type: Number, default: 0 },

    // A customer paying €50 with €30 cash and €20 on card produces two entries
    // here; paymentMethod is then "split".
    payments: [
      {
        _id: false,
        method: {
          type: String,
          // "wallet" covers digital/online tenders (Apple Pay, Google Pay, Revolut).
          enum: ["cash", "creditcard", "credit", "wallet"],
          required: true,
        },
        amount: { type: Number, required: true },
      },
    ],
    paymentMethod: {
      type: String,
      enum: ["cash", "creditcard", "credit", "wallet", "split"],
      required: true,
    },
    amountTendered: { type: Number },
    changeDue: { type: Number },

    status: {
      type: String,
      enum: ["completed", "voided", "partially-refunded", "refunded"],
      default: "completed",
    },
    refunds: [RefundEntrySchema],

    // Set once the cashier closes their day. Unset (null) means the receipt is
    // still on that cashier's own sale history; stamped means it has been
    // handed over to the admin and no longer shows for the cashier.
    dayClosing: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DayClosing",
      default: null,
    },

    // Rung up while the till had no network, then synced.
    //
    // `clientRef` is generated by the till and is what makes syncing safe to
    // retry: a receipt already carrying it is never written twice, so a flaky
    // connection can replay the queue without charging the customer again.
    //
    // The customer's printed receipt shows `offline.ref`, so a refund must be
    // findable by that as well as by the sequential receiptNo assigned here.
    offline: {
      clientRef: { type: String },
      ref: { type: String },
      soldAt: { type: Date },
      syncedAt: { type: Date },
      // Anything the server would have done differently had it been online.
      // Surfaced to the admin rather than silently "corrected", because the
      // goods and the printed receipt are already out of the shop.
      flags: [
        {
          _id: false,
          type: {
            type: String,
            enum: ["negative-stock", "price-changed", "deal-changed", "voucher-spent"],
          },
          product: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
          name: { type: String },
          detail: { type: String },
        },
      ],
    },

    saleIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "Sale" }],
  },
  { timestamps: true }
);

// Idempotency key for offline sync: at most one receipt per till-generated ref.
// Sparse, because online sales have no clientRef at all.
ReceiptSchema.index(
  { "offline.clientRef": 1 },
  { unique: true, sparse: true }
);
ReceiptSchema.index({ "offline.ref": 1 }, { sparse: true });
// Ghost/report exports commonly slice a full trading year by date, then narrow
// by cashier or status. These indexes keep those reads bounded without touching
// the immutable receipt records.
ReceiptSchema.index({ createdAt: -1 });
ReceiptSchema.index({ cashier: 1, createdAt: -1 });
ReceiptSchema.index({ status: 1, createdAt: -1 });

const Receipt = mongoose.model("Receipt", ReceiptSchema);

module.exports = Receipt;
