// Small dependency-free CSV builder with proper escaping and date formatting.

const { formatInZone } = require("./time");

const pad = (n) => String(n).padStart(2, "0");

const formatDate = (value) => {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

const formatDateTime = (value) => {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(
    d.getHours()
  )}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
};

const money = (value) => {
  const n = Number(value || 0);
  return n.toFixed(2);
};

const escapeCell = (value) => {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const toRow = (cells) => cells.map(escapeCell).join(",");

/**
 * Build a CSV document:
 *   Shop name / address        <- whose figures these are
 *   Title / period
 *   Generated / by / records / currency
 *   (blank line)
 *   header row
 *   data rows
 *   SUMMARY
 *
 * The money columns stay as bare numbers here on purpose: a CSV exists to be
 * summed and pivoted, and "€12.00" imports as text. The currency is stated in
 * the header block instead.
 */
const buildCsv = ({
  title,
  subtitle,
  generatedBy,
  headers,
  rows,
  summary,
  shop = {},
  currency = "EUR",
  timezone = "UTC",
}) => {
  const lines = [];

  if (shop.name) lines.push(toRow([shop.name]));
  const address = [...(shop.addressLines || []), shop.phone].filter(Boolean).join(", ");
  if (address) lines.push(toRow([address]));
  if (shop.name) lines.push("");

  lines.push(toRow([title]));
  if (subtitle) lines.push(toRow([subtitle]));
  lines.push(toRow(["Generated", formatInZone(new Date(), timezone)]));
  if (generatedBy) lines.push(toRow(["Generated by", generatedBy]));
  lines.push(toRow(["Total records", rows.length]));
  lines.push(toRow(["Currency", currency]));
  lines.push(toRow(["Timezone", timezone]));
  lines.push("");
  lines.push(toRow(headers));
  rows.forEach((r) => lines.push(toRow(r)));

  if (summary && summary.length) {
    lines.push("");
    lines.push(toRow(["SUMMARY"]));
    summary.forEach(([label, value]) => lines.push(toRow([label, value])));
  }

  // Prepend BOM so Excel opens UTF-8 correctly.
  return "﻿" + lines.join("\r\n");
};

module.exports = { buildCsv, formatDate, formatDateTime, money };
