// Small dependency-free CSV builder with proper escaping and date formatting.

const pad = (n) => String(n).padStart(2, "0");

const formatDate = (value) => {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

const formatDateTime = (value) => {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(
    d.getHours()
  )}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
};

const money = (value) => {
  const n = Number(value || 0);
  return n.toFixed(2);
};

const escapeCell = (value) => {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const toRow = (cells) => cells.map(escapeCell).join(",");

/**
 * Build a professional CSV document:
 *   Title
 *   Generated / Generated by / Total records metadata
 *   (blank line)
 *   header row
 *   data rows
 */
const buildCsv = ({ title, subtitle, generatedBy, headers, rows, summary }) => {
  const lines = [];
  lines.push(toRow([title]));
  if (subtitle) lines.push(toRow([subtitle]));
  lines.push(toRow(["Generated", formatDateTime(new Date())]));
  if (generatedBy) lines.push(toRow(["Generated by", generatedBy]));
  lines.push(toRow(["Total records", rows.length]));
  lines.push("");
  lines.push(toRow(headers));
  rows.forEach((r) => lines.push(toRow(r)));

  if (summary && summary.length) {
    lines.push("");
    lines.push(toRow(["SUMMARY"]));
    summary.forEach(([label, value]) => lines.push(toRow([label, value])));
  }

  // Prepend BOM so Excel opens UTF-8 correctly.
  return "﻿" + lines.join("\r\n");
};

module.exports = { buildCsv, formatDate, formatDateTime, money };
