const ExcelJS = require("exceljs");
const { formatInZone } = require("./time");
const { excelMoneyFormat, symbolFor } = require("./money");

// Columns whose header matches this are treated as numbers (money/quantities),
// so Excel right-aligns them and never shows ####. Everything else stays text
// (prevents barcodes turning into 6.29E+12 and dates auto-reformatting).
const NUMERIC_HEADER = /(qty|quantity|price|cost|total|value|profit|revenue|discount|tax|amount|units|sales|net|gross|refunded)/i;
const MONEY_HEADER = /(price|cost|total|value|profit|revenue|discount|tax|amount|net|gross|refunded)/i;

const toNumber = (v) => {
  const n = Number(String(v).replace(/[^0-9.-]/g, ""));
  return Number.isNaN(n) ? null : n;
};

/**
 * Build a styled .xlsx workbook buffer from a report definition.
 * Same shape as the CSV builder:
 *   { title, subtitle, generatedBy, headers, rows, summary, shop, currency }
 */
async function buildWorkbookBuffer({
  title,
  subtitle,
  generatedBy,
  headers,
  rows,
  summary,
  shop = {},
  currency = "EUR",
  timezone = "UTC",
}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = shop.name || "E360 Inventory Suite";
  wb.created = new Date();
  const ws = wb.addWorksheet("Report", {
    views: [{ state: "normal" }],
    pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  });

  const colCount = headers.length;
  const numericCol = headers.map((h) => NUMERIC_HEADER.test(h));
  const moneyCol = headers.map((h) => MONEY_HEADER.test(h));
  const moneyFmt = excelMoneyFormat(currency);

  // ── Letterhead: whose figures these are. A spreadsheet gets emailed on and
  // opened out of context, so it has to say for itself.
  const shopRow = ws.addRow([shop.name || ""]);
  shopRow.font = { bold: true, size: 14 };
  ws.mergeCells(shopRow.number, 1, shopRow.number, colCount);

  const address = [...(shop.addressLines || []), shop.phone].filter(Boolean).join("  ·  ");
  if (address) {
    const addr = ws.addRow([address]);
    addr.font = { size: 9, color: { argb: "FF64748B" } };
    ws.mergeCells(addr.number, 1, addr.number, colCount);
  }

  // ── Title + metadata block ──
  const titleRow = ws.addRow([title]);
  titleRow.font = { bold: true, size: 16, color: { argb: "FF1D4ED8" } };
  ws.mergeCells(titleRow.number, 1, titleRow.number, colCount);

  if (subtitle) {
    const sub = ws.addRow([subtitle]);
    sub.font = { italic: true, size: 11, color: { argb: "FF64748B" } };
    ws.mergeCells(sub.number, 1, sub.number, colCount);
  }
  [
    ["Generated", formatInZone(new Date(), timezone)],
    ["Generated by", generatedBy || ""],
    ["Total records", rows.length],
    // Never leave the reader guessing what the numbers are, or which clock.
    ["Currency", `${currency} (${symbolFor(currency)})`],
    ["Timezone", timezone],
  ].forEach(([label, value]) => {
    const row = ws.addRow([label, value]);
    row.getCell(1).font = { bold: true, color: { argb: "FF64748B" } };
  });

  ws.addRow([]); // spacer

  // ── Header row ──
  const headerRow = ws.addRow(headers);
  headerRow.eachCell((cell, col) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E293B" } };
    cell.alignment = {
      vertical: "middle",
      horizontal: numericCol[col - 1] ? "right" : "left",
    };
    cell.border = { bottom: { style: "thin", color: { argb: "FFCBD5E1" } } };
  });

  // Headers stay put while scrolling, and can be filtered — the difference
  // between a dump and something you can actually work in.
  ws.views = [{ state: "frozen", ySplit: headerRow.number }];
  ws.autoFilter = {
    from: { row: headerRow.number, column: 1 },
    to: { row: headerRow.number, column: colCount },
  };

  // ── Data rows ──
  rows.forEach((r) => {
    const values = r.map((v, i) => {
      if (numericCol[i]) {
        const n = toNumber(v);
        if (n !== null) return n;
      }
      return v === null || v === undefined ? "" : String(v);
    });
    const row = ws.addRow(values);
    row.eachCell({ includeEmpty: true }, (cell, col) => {
      if (numericCol[col - 1]) {
        // Real numbers with a real currency format, so the reader can sum a
        // column and Excel shows it in the shop's money.
        cell.numFmt = moneyCol[col - 1] ? moneyFmt : "#,##0";
        cell.alignment = { horizontal: "right" };
      } else {
        cell.numFmt = "@"; // force text
      }
    });
  });

  // ── Summary block ──
  if (summary && summary.length) {
    ws.addRow([]);
    const sh = ws.addRow(["SUMMARY"]);
    sh.getCell(1).font = { bold: true, size: 12, color: { argb: "FF1D4ED8" } };
    sh.getCell(1).border = { bottom: { style: "medium", color: { argb: "FF1D4ED8" } } };

    summary.forEach(([label, value]) => {
      const row = ws.addRow([label, value]);
      row.getCell(1).font = { bold: true };

      const n = toNumber(value);
      if (n !== null && /profit|sales|revenue|cost|value|discount|tax|amount|net|gross|refunded|takings/i.test(label)) {
        row.getCell(2).value = n;
        row.getCell(2).numFmt = moneyFmt;
        row.getCell(2).alignment = { horizontal: "right" };
        row.getCell(2).font = { bold: true };
      }
    });
  }

  // ── Column widths from header + data (+ summary labels) ──
  const widths = headers.map((h) => String(h).length);
  rows.forEach((r) =>
    r.forEach((v, i) => {
      const len = String(v ?? "").length;
      if (len > (widths[i] || 0)) widths[i] = len;
    })
  );
  if (summary && summary.length) {
    const labelMax = Math.max(...summary.map(([l]) => String(l).length));
    if (labelMax > (widths[0] || 0)) widths[0] = labelMax;
  }
  ws.columns.forEach((col, i) => {
    col.width = Math.min(Math.max((widths[i] || 10) + 2, 10), 45);
  });

  return wb.xlsx.writeBuffer();
}

module.exports = { buildWorkbookBuffer };
