const ExcelJS = require("exceljs");
const { formatDateTime } = require("./csv");

// Columns whose header matches this are treated as numbers (money/quantities),
// so Excel right-aligns them and never shows ####. Everything else stays text
// (prevents barcodes turning into 6.29E+12 and dates auto-reformatting).
const NUMERIC_HEADER = /(qty|quantity|price|cost|total|value|profit|revenue|discount|tax|amount|units)/i;
const MONEY_HEADER = /(price|cost|total|value|profit|revenue|discount|tax|amount)/i;

const toNumber = (v) => {
  const n = Number(String(v).replace(/,/g, ""));
  return Number.isNaN(n) ? null : n;
};

/**
 * Build a styled .xlsx workbook buffer from a report definition.
 * Same shape as the CSV builder: { title, subtitle, generatedBy, headers, rows, summary }.
 */
async function buildWorkbookBuffer({ title, subtitle, generatedBy, headers, rows, summary }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Inventory Management System";
  wb.created = new Date();
  const ws = wb.addWorksheet("Report");

  const colCount = headers.length;
  const numericCol = headers.map((h) => NUMERIC_HEADER.test(h));
  const moneyCol = headers.map((h) => MONEY_HEADER.test(h));

  // ── Title + metadata block ──
  const titleRow = ws.addRow([title]);
  titleRow.font = { bold: true, size: 16 };
  ws.mergeCells(titleRow.number, 1, titleRow.number, colCount);

  if (subtitle) {
    const sub = ws.addRow([subtitle]);
    sub.font = { italic: true, size: 11, color: { argb: "FF64748B" } };
    ws.mergeCells(sub.number, 1, sub.number, colCount);
  }
  [["Generated", formatDateTime(new Date())], ["Generated by", generatedBy || ""], ["Total records", rows.length]]
    .forEach(([label, value]) => {
      const row = ws.addRow([label, value]);
      row.getCell(1).font = { bold: true, color: { argb: "FF64748B" } };
    });

  ws.addRow([]); // spacer

  // ── Header row ──
  const headerRow = ws.addRow(headers);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E293B" } };
    cell.alignment = { vertical: "middle" };
    cell.border = { bottom: { style: "thin", color: { argb: "FFCBD5E1" } } };
  });

  // ── Data rows ──
  rows.forEach((r) => {
    const values = r.map((v, i) => {
      if (numericCol[i]) {
        const n = toNumber(v);
        if (n !== null) return n;
      }
      return v === null || v === undefined ? "" : String(v);
    });
    const row = ws.addRow(values);
    row.eachCell({ includeEmpty: true }, (cell, col) => {
      if (numericCol[col - 1]) {
        cell.numFmt = moneyCol[col - 1] ? "#,##0.00" : "#,##0";
        cell.alignment = { horizontal: "right" };
      } else {
        cell.numFmt = "@"; // force text
      }
    });
  });

  // ── Summary block ──
  if (summary && summary.length) {
    ws.addRow([]);
    const sh = ws.addRow(["SUMMARY"]);
    sh.getCell(1).font = { bold: true, size: 12 };
    summary.forEach(([label, value]) => {
      const row = ws.addRow([label, value]);
      row.getCell(1).font = { bold: true };
      const n = toNumber(value);
      if (n !== null && /profit|sales|revenue|cost|value|discount|tax|amount/i.test(label)) {
        row.getCell(2).value = n;
        row.getCell(2).numFmt = "#,##0.00";
      }
    });
  }

  // ── Column widths from header + data (+ summary labels) ──
  const widths = headers.map((h) => String(h).length);
  rows.forEach((r) =>
    r.forEach((v, i) => {
      const len = String(v ?? "").length;
      if (len > (widths[i] || 0)) widths[i] = len;
    })
  );
  if (summary && summary.length) {
    const labelMax = Math.max(...summary.map(([l]) => String(l).length));
    if (labelMax > (widths[0] || 0)) widths[0] = labelMax;
  }
  ws.columns.forEach((col, i) => {
    col.width = Math.min(Math.max((widths[i] || 10) + 2, 10), 45);
  });

  return wb.xlsx.writeBuffer();
}

module.exports = { buildWorkbookBuffer };
